PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^ProductClass/', include('apps.ProductClass.urls', namespace='ProductClass')),  # 商品类别模块
    url(r'^ProductInfo/', include('apps.ProductInfo.urls', namespace='ProductInfo')),  # 产品信息模块
    url(r'^Supplyer/', include('apps.Supplyer.urls', namespace='Supplyer')),  # 供应商模块
    url(r'^CustomerInfo/', include('apps.CustomerInfo.urls', namespace='CustomerInfo')),  # 客户信息模块
    url(r'^BuyInfo/', include('apps.BuyInfo.urls', namespace='BuyInfo')),  # 产品进货模块
    url(r'^SellInfo/', include('apps.SellInfo.urls', namespace='SellInfo')),  # 产品销售模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/BuyInfo/urls.py
from apps.BuyInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'BuyInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<buyId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<buyId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<buyId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<buyId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/templates/check_logstate.html
{% if not request.session.username %}
<script>top.location.href='{% url 'Index:login' %}';</script>
{% endif %}

PythonProject/templates/footer.html
<!--footer-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            	<a href="http://www.baidu.com" target=_blank>© 大神开发网 from 2020</a> |
				<a href="http://www.baidu.com">本站招聘</a> |
				<a href="http://www.baidu.com">联系站长</a> |
				<a href="http://www.baidu.com">意见与建议</a> |
				<a href="http://www.baidu.com" target=_blank>湘ICP备0703346号</a> |
				<a href="{% url 'Index:login' %}">后台登录</a>
            </div>
        </div>
    </div>
</footer>
<!--footer-->

PythonProject/templates/header.html
<!--导航开始-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'Index:index' %}" class="navbar-brand">商品进销存系统</a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'Index:index' %}">首页</a></li>
                        <li><a href="{% url 'ProductClass:frontList' %}">商品类别</a></li>
                        <li><a href="{% url 'ProductInfo:frontList' %}">产品信息</a></li>
                        <li><a href="{% url 'Supplyer:frontList' %}">供应商</a></li>
                        <li><a href="{% url 'CustomerInfo:frontList' %}">客户信息</a></li>
                        <li><a href="{% url 'BuyInfo:frontList' %}">产品进货</a></li>
                        <li><a href="{% url 'SellInfo:frontList' %}">产品销售</a></li>

            </ul>

             <ul class="nav navbar-nav navbar-right">
             	{% if not request.session.user_name %}
	  			<li><a href="#" onclick="register();" style="display:none;"><i class="fa fa-sign-in"></i>&nbsp;&nbsp;注册</a></li>
                <li><a href="#" onclick="login();" style="display:none;"><i class="fa fa-user"></i>&nbsp;&nbsp;登录</a></li>

                {% else %}
                <li class="dropdown">
                    <a id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ request.session.user_name }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dLabel">
                        <li><a href="{% url 'Index:index' %}"><span class="glyphicon glyphicon-screenshot"></span>&nbsp;&nbsp;首页</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;发布信息</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-cog"></span>&nbsp;&nbsp;我发布的信息</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-credit-card"></span>&nbsp;&nbsp;修改个人资料</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-heart"></span>&nbsp;&nbsp;我的收藏</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'Index:frontLoginout' %}"><span class="glyphicon glyphicon-off"></span>&nbsp;&nbsp;退出</a></li>
                {% endif %}
            </ul>

        </div>
        <!--导航-->
    </div>
</nav>
<!--导航结束-->


<div id="loginDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-key"></i>&nbsp;系统登录</h4>
      </div>
      <div class="modal-body">
      	<form class="form-horizontal" name="loginForm" id="loginForm" enctype="multipart/form-data" method="post"  class="mar_t15">

      	  <div class="form-group">
			 <label for="userName" class="col-md-3 text-right">用户名:</label>
			 <div class="col-md-9">
			 	<input type="text" id="userName" name="userName" class="form-control" placeholder="请输入用户名">
			 </div>
		  </div>

      	  <div class="form-group">
		  	 <label for="password" class="col-md-3 text-right">密码:</label>
		  	 <div class="col-md-9">
			    <input type="password" id="password" name="password" class="form-control" placeholder="登录密码">
			 </div>
		  </div>

		</form>
	    <style>#bookTypeAddForm .form-group {margin-bottom:10px;}  </style>
      </div>
      <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
		<button type="button" class="btn btn-primary" onclick="ajaxLogin();">登录</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

 {% csrf_token %}



<div id="registerDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-sign-in"></i>&nbsp;用户注册</h4>
      </div>
      <div class="modal-body">
      	<form class="form-horizontal" name="registerForm" id="registerForm" enctype="multipart/form-data" method="post"  class="mar_t15">



		</form>
	    <style>#bookTypeAddForm .form-group {margin-bottom:10px;}  </style>
      </div>
      <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
		<button type="button" class="btn btn-primary" onclick="ajaxRegister();">注册</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->






<script>

function register() {
	$("#registerDialog input").val("");
	$("#registerDialog textarea").val("");
	$('#registerDialog').modal('show');
}
function ajaxRegister() {
	$("#registerForm").data('bootstrapValidator').validate();
	if(!$("#registerForm").data('bootstrapValidator').isValid()){
		return;
	}

	jQuery.ajax({
		type : "post" ,
		url : "add",
		dataType : "json" ,
		data: new FormData($("#registerForm")[0]),
		success : function(obj) {
			if(obj.success){
                alert("注册成功！");
                $("#registerForm").find("input").val("");
                $("#registerForm").find("textarea").val("");
            }else{
                alert(obj.message);
            }
		},
		processData: false,
	    contentType: false,
	});
}


function login() {
	$("#loginDialog input").val("");
	$('#loginDialog').modal('show');
}
function ajaxLogin() {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	$.ajax({
		url : "{% url 'Index:frontLogin' %}",
		type : 'post',
		dataType: "json",
		data : {
			"userName" : $('#userName').val(),
			"password" : $('#password').val(),
            "csrfmiddlewaretoken": csrf
		},
		success : function (obj, response, status) {
			if (obj.success) {
				location.href = "{% url 'Index:index' %}";
			} else {
				alert(obj.msg);
			}
		}
	});
}


</script>

PythonProject/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <title>精品项目设计-首页</title>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
{% include 'header.html' %}
 <!-- 广告轮播开始 -->
  <section id="main_ad" class="carousel slide" data-ride="carousel">
    <!-- 下面的小点点，活动指示器 -->
    <ol class="carousel-indicators">
      <li data-target="#main_ad" data-slide-to="0" class="active"></li>
      <li data-target="#main_ad" data-slide-to="1"></li>
      <li data-target="#main_ad" data-slide-to="2"></li>
      <li data-target="#main_ad" data-slide-to="3"></li>
    </ol>
    <!-- 轮播项 -->
    <div class="carousel-inner" role="listbox">
      <div class="item active" data-image-lg="{% static 'images/slider/slide_01_2000x410.jpg' %}" data-image-xs="{% static 'images/slider/slide_01_640x340.jpg' %}"></div>
      <div class="item" data-image-lg="{% static 'images/slider/slide_02_2000x410.jpg' %}" data-image-xs="{% static 'images/slider/slide_02_640x340.jpg' %}"></div>
      <div class="item" data-image-lg="{% static 'images/slider/slide_03_2000x410.jpg' %}" data-image-xs="{% static 'images/slider/slide_03_640x340.jpg' %}"></div>
      <div class="item" data-image-lg="{% static 'images/slider/slide_04_2000x410.jpg' %}" data-image-xs="{% static 'images/slider/slide_04_640x340.jpg' %}"></div>
    </div>
    <!-- 控制按钮 -->
    <a class="left carousel-control" href="#main_ad" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">上一页</span>
    </a>
    <a class="right carousel-control" href="#main_ad" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">下一页</span>
    </a>
  </section>
  <!-- /广告轮播结束 -->


<!-- 特色介绍开始 -->
  <section id="tese">
    <div class="container">
      <div class="row">
        <div class="col-xs-6 col-md-4">
          <a href="#">
            <div class="media">
              <div class="media-left">
                <i class="icon-uniE907"></i>
              </div>
              <div class="media-body">
                <h4 class="media-heading">精品设计制作</h4>
                <p>此设计已经通过了精心调试</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-xs-6 col-md-4">
          <a href="#">
            <div class="media">
              <div class="media-left">
                <i class="icon-uniE907"></i>
              </div>
              <div class="media-body">
                <h4 class="media-heading">精品设计制作</h4>
                <p>此设计已经通过了精心调试</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-xs-6 col-md-4">
          <a href="#">
            <div class="media">
              <div class="media-left">
                <i class="icon-uniE907"></i>
              </div>
              <div class="media-body">
                <h4 class="media-heading">精品设计制作</h4>
                <p>此设计已经通过了精心调试</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-xs-6 col-md-4">
          <a href="#">
            <div class="media">
              <div class="media-left">
                <i class="icon-uniE907"></i>
              </div>
              <div class="media-body">
                <h4 class="media-heading">精品设计制作</h4>
                <p>此设计已经通过了精心调试</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-xs-6 col-md-4">
          <a href="#">
            <div class="media">
              <div class="media-left">
                <i class="icon-uniE907"></i>
              </div>
              <div class="media-body">
                <h4 class="media-heading">精品设计制作</h4>
                <p>此设计已经通过了精心调试</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-xs-6 col-md-4">
          <a href="#">
            <div class="media">
              <div class="media-left">
                <i class="icon-uniE907"></i>
              </div>
              <div class="media-body">
                <h4 class="media-heading">精品设计制作</h4>
                <p>此设计已经通过了精心调试</p>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </section>
  <!-- /特色介绍 结束-->

{% include 'footer.html' %}

</div>
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
</body>
</html>

PythonProject/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>信息管理系统_用户登录</title>

<link rel="stylesheet" type="text/css" href="{%  static 'easyui/themes/default/easyui.css' %}" />
<link rel="stylesheet" type="text/css" href="{%  static 'easyui/themes/icon.css' %}" />
<link rel="stylesheet" type="text/css" href="{%  static 'css/login.css' %}" />
</head>
<body>

<div id="login">
	<p>登录帐号：<input type="text"  id="manager" class="textbox"></p>
	<p>登录密码：<input type="password" id="password" class="textbox"></p>
    {% csrf_token %}
	<p style="display:none;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;身份：
		<select name="identify" id="identify">
			<option value="admin">超级管理员</option>
			<option value="departAdmin">部门管理员</option>
			<option value="ssAdmin">实施人员</option>
			<option value="kfAdmin">客服人员</option>
		</select>
	</p>
	<p> <font color="#999">记住账号</font>
		<input  id="saveid" type="checkbox"  onclick="savePaw();"  />
	</p>

</div>

<div id="btn">
	<a href="#" class="easyui-linkbutton">登录</a>
</div>

<script type="text/javascript" src="{%  static 'easyui/jquery.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'easyui/jquery.easyui.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'easyui/locale/easyui-lang-zh_CN.js' %}" ></script>
<script type="text/javascript" src="{%  static 'easyui/jquery.cookie.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/login.js' %}"></script>

</body>
</html>
</html>

PythonProject/templates/main.html
{% include 'check_logstate.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>信息管理系统</title>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'easyui/themes/default/easyui.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'easyui/themes/icon.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/admin.css' %}" />
</head>
<body class="easyui-layout">

<div data-options="region:'north',title:'header',split:true,noheader:true" style="height:60px;background-color:rgb(108, 175, 135);">
	<div class="logo">Python商品销售进销存管理后台管理</div>
	<div class="logout">您好，{{ request.session.username }}| <a href="{% url 'Index:loginout' %}">退出</a></div>
</div>
<div data-options="region:'south',title:'footer',split:true,noheader:true" style="height:35px;line-height:30px;text-align:center;">
	&copy; Powered by dashen
</div>
<div data-options="region:'west',title:'导航',split:true,iconCls:'icon-world'" style="width:200px;padding:10px;">
	<ul id="nav"></ul>
</div>
<div data-options="region:'center'" style="overflow:hidden;">
	<div id="tabs">
		<div title="起始页" iconCls="icon-house" style="padding:0 10px;display:block;font-size:70px">
			<br/><br/> <center>欢迎来到后台管理系统！</center>
		</div>
	</div>
</div>


<script type="text/javascript" src="{% static 'easyui/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'easyui/jquery.easyui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'easyui/locale/easyui-lang-zh_CN.js' %}" ></script>
<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script type="text/javascript" src="{% static 'js/admin.js' %}"></script>


</body>
</html>

PythonProject/templates/message.html
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>错误提示</title>
<link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center"><table width="419" height="226" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" background="{% static 'images/error.jpg' %}"><table width="388" height="194" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td align="center"><img src="{% static 'images/error_b.gif' %}" width="31" height="31">&nbsp;&nbsp; {{ message }} <br>
              <br>
              </td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
</table>
</body>
</html>

PythonProject/templates/password_modify.html
{% include 'check_logstate.html' %}
<!DOCTYPE html>
<html>
<HEAD><TITLE>修改密码</TITLE>
<STYLE type=text/css>
BODY {
	MARGIN-LEFT: 0px; BACKGROUND-COLOR: #ffffff
}
</STYLE>
</HEAD>
<BODY>

<TABLE align="center"   cellSpacing=0 cellPadding=0 width="80%" border=0>
  <TBODY>
  <TR>
    <TD align="left" vAlign=top >
        <br>
        <form action="{% url 'Index:changePassword' %}" method="post" name="form1" target="submitFrame">
        {% csrf_token %}
<table width='100%' cellspacing='1' cellpadding='3' bgcolor='#CCCCCC' class="tablewidth">
  <tr>
  	<td align="right" width="35%">以前的密码:</td>
    <td width=65%><input name="oldPassword" type=password /></td>
  </tr>
 <tr>
  	<td align="right" width="35%">输入新密码:</td>
    <td width=65%><input name="newPassword" type=password /></td>
  </tr>
  <tr>
  	<td align="right" width="35%">再输入新密码:</td>
    <td width=65%><input name="newPassword2" type=password /></td>
  </tr>
  <tr bgcolor='#FFFFFF'>
      <td colspan="4" align="center">
        <input type='submit' name='button' value='修改密码' >
        &nbsp;&nbsp;
      </td>
    </tr>
</table>
</form>
 <iframe name="submitFrame" frameborder="0" scrolling="yes" width="100%" height="300px"></iframe>
   </TD>
	</TR>
  </TBODY>
</TABLE>
</BODY>
</HTML>